apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: list-app-ingress
spec:
  rules:
  - host: list-app.local
    http:
      paths:
      - path: /signup
        pathType: Prefix
        backend:
          service:
            name: list-app-svc
            port:
              number: 5000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: list-app-svc
            port:
              number: 5002
