apiVersion: v1
kind: Service
metadata:
  name: list-app-svc
spec:
  selector:
    app: list-app
  ports:
  - name: signup
    port: 5000
    targetPort: 5000
  - name: users
    port: 5002
    targetPort: 5002
